### PR TITLE
Fixed reap_playwright_servers issue, js confirm dialog, macos build, cleanup argument

### LINKED ISSUE #62: reap_playwright_servers - too few arguments to Playwright::Util::request
Hi. I'm finally converting my Selenium tests to Playwright. Thank you!

I tried to run `reap_playwright_servers` but it gives an error:

```
Too few arguments for subroutine 'Playwright::Util::request' (got 4; expected at least 5) at /usr/local/bin/reap_playwright_servers line 29.
 at /usr/local/bin/reap_playwright_servers line 29.
```

It looks like https://github.com/teodesian/playwright-perl/issues/51 added a $host argument. If I add 'localhost' to the  Playwright::Util::request() call in reap_playwright_servers it works fine.

I would be happy to create a pull request but wanted your thoughts.

### PR DESCRIPTION
**Pull request by kcaran**
Hi George. I was able to convert my main Selenium-based suite of tests to Playwright.pm. This is amazing work, thank you! It's so much easier to get tests up and running.

The issues I ran into are minor and I've tried to fix them here. 

* Able to build on MacOS - There is no /bin/true on my machine and I can't rely on /usr/bin/perl (or much of /usr/bin anything). I modified paths only where it prevented me from building.
* reap_playwright_servers - Fixed #62 and wrote an author test to confirm it is working as intended. As I'm sure you're aware, the addition of the nodejs files makes it challenging to get tests running in every environment. I haven't given up on getting them to work during install (and automating the nodejs install) but I'm not quite there.
* I added a one second sleep at the bottom of reap_playwright_servers. At least on my laptop, reaping servers corrupted the shell input on return. This seems to fix it.
* cleanup => 0 wasn't working as intended. I included this in the reap_playwright_servers test.
* JavaScript confirm dialog support - The $page->on() function wasn't being processed correctly by playwright_server if it required more than one argument. It was a simple change to get working and I added xt/author/js_dialogs.t to show the fix is working as intended.
* dist.ini - I added author tests under xt (which hopefully can turn into standard tests). Trying to run `dzil build` was extremely slow, which I narrowed down to the PkgVersion plugin trying to parse playwright_server after the spec was loaded. I added configuration so it will ignore that file.

I know this looks like a lot but the changes I had to make to the existing code were minimal. I think being able to run tests directly from the repository will be really useful. This gets my code up and running, but it really is just a first attempt and I am willing to respond to your feedback. Thanks agan!

### CODE REVIEW

File: bin/reap_playwright_servers [hunk 1]
```diff
@@ -26,9 +26,12 @@ sub main {
        my ($port) = $process->cmndline =~ m/playwright_server --port (\d+)/;
        next unless $port;
        print "Instructing playwright_server process ".$process->pid()." listening on $port to shut down...\n";
-       Playwright::Util::request( 'GET', 'shutdown', $port, $ua );
+       Playwright::Util::request( 'GET', 'shutdown', 'localhost', $port, $ua );
     }
 
+    # Make sure everything is shut down before returning
+    sleep 1 if (@matches);
```
Comment (teodesian) [inline bin/reap_playwright_servers:33]: Probably a better way to do this.  I'll file a follow up case on it, and not block merge for this.

File: lib/Playwright.pm [hunk 2]
```diff
@@ -751,7 +752,7 @@ sub _start_server ( $port, $cdp_uri, $timeout, $debug, $cleanup ) {
     # Orphan the process in the event that cleanup => 0
     if (!$cleanup) {
         print "Detaching child process...\n";
-        chdir '/';
+        #chdir '/';
```
Comment (teodesian) [inline lib/Playwright.pm:755]: Chdir into some dir is good for safety of daemonized processes.

I'll file an issue to send it into a File::Temp::tempdir instead.

File: playwright_server [hunk 3]
```diff
@@ -8,6 +8,7 @@ const fs = require('fs');
 const path = require('path');
 
 // Assume their kit is good
+module.paths.push( '/usr/local/lib/node_modules' );
```
Comment (teodesian) [inline playwright_server:11]: There's probably a better way to figure out how to consult "system node" modules.  npm config ls -l seems in the right neighborhood?. npx-import seems like a crazy solution to the problem.

I generally use NVM and that just sets the node lib env correctly.
I'll file a follow up about this.

File: playwright_server [hunk 4]
```diff
@@ -273,7 +274,7 @@ app.post('/command', async (req, res) => {
     } else if (command == 'on' && subject && spec[type].members.waitForEvent ) {
         try {
             var evt = args.shift();
-            const cb  = new Function (args.shift());
+            const cb  = new Function (...args);
```
Comment (teodesian) [inline playwright_server:277]: Interesting.  I'm not sure we'll ever need this, but it's a welcome addition.

File: xt/author/reap_playwright_servers.t
Comment (teodesian) [inline xt/author/reap_playwright_servers.t:1]: I'll remove the test at the end of the at/ test in favor of this one.

I probably should have made everything XT in the first place.

File: generate_api_json.sh [hunk 5]
```diff
@@ -1,13 +1,13 @@
...
-mkdir bin; /bin/true
+mkdir bin; true
 pushd ../playwright
 git pull
 node utils/doclint/generateApiJson.js > ../playwright-perl/api.json
 popd
 cp playwright_server bin/playwright_server
 API="$(<api.json)"
-sed -i -e '/%REPLACEME%/r api.json' -e 's/%REPLACEME%//g' bin/playwright_server
+sed -i '' -e '/%REPLACEME%/r api.json' -e 's/%REPLACEME%//g' bin/playwright_server
```
Comment (teodesian) [inline generate_api_json.sh:11]: IIRC there's no need to supply a blank suffix for backing up the file -- does OSX sed explode on this?

Comment (teodesian) [reply generate_api_json.sh:11]: Yeah, this breaks linux.  According to the OSX manpage for sed, the old behavior should be what is preferred.  I am going to back this particular patch out.

Comment (teodesian) [reply generate_api_json.sh:11]: 67467610fd69677f0d836361b785773f286eea86

File: playwright_server (hunk 4 above)
Comment (teodesian) [reply playwright_server:277]: Indeed.  I realized that as I had to modify the xt test to survive dzil release.  Thanks for the great patchset.
